---
name: Get ISO

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
jobs:
  Get:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Build script
        id: build
        run: |
          brew install coreutils || true
          for i in 1 2 3 4 5 6 7 8
          do
          bash ./2016.sh -set${i}
          for i in *.iso
          do
          gh release upload 2016 $i --clobber
          done
          rm ./*.iso
          done
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: office
          path: ${{ github.workspace }}/sha256sum.txt

      - name: Release
        if: false
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/*.ISO
          tag_name: 2016
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
