---
name: Get ISO

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
jobs:
  Get:
    runs-on: ubuntu-24.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
          verbose: 'true'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Build script
        id: build
        run: |
          sudo apt update
          sudo apt install megatools -y
          megadl https://mega.nz/folder/ryAQTahK#jNXjQ1WQM3gOcymWiCm71Q/folder/3r4SES5D
          wget https://github.com/AdityaGarg8/Office-ISO-Archive/releases/download/Test/en_office_2003_pro.iso
          wget https://www.smartversion.com/smartvs400_linux_x64.zip
          unzip smartvs400_linux_x64.zip
          for i in *.svf
          do
          ./smv x ${i} -br ./
          done
          sha256sum *.iso > sha256

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: office
          path: ${{ github.workspace }}/sha256

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/*.iso
            ${{ github.workspace }}/sha256
          tag_name: 2003
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
