---
name: Get ISO

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
jobs:
  Get:
    runs-on: ubuntu-24.04
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Build script
        id: build
        run: |
          bash ./2007.sh -set4
          sha256sum ./*.iso > sha256sum.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: office
          path: ${{ github.workspace }}/sha256sum.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/*.iso
          tag_name: 2007
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
